name: CI/CD for WebSocket App

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Give executable permissions to gradlew
        run: chmod +x ./gradlew

      - name: Build the project
        run: ./gradlew build

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t gery12492/web-socket:1.0.0 .

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Raspberry Pi
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no pi@pingnest.ddns.net << 'EOF'
          docker stop websocket-app || true
          docker rm websocket-app || true
          docker run -d --name websocket-app --network my-network -p 8081:8081 gery12492/web-socket:latest
          EOF
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
