name: CI/CD for WebSocket App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give executable permissions to gradlew
        run: chmod +x ./gradlew

      - name: Check Java version
        run: java -version

      - name: Clean the project
        run: ./gradlew clean

      - name: Build the project
        run: ./gradlew build

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for multiple architectures
        run: |
          docker buildx create --use
          docker buildx build --no-cache --platform linux/arm/v7,linux/amd64  -t gery12492/web-socket:1.0.0 --push .

      - name: Confirm Docker image push
        run: docker images

      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy to Raspberry Pi
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no pi@pingnest.ddns.net << 'EOF'
          docker stop websocket-app || true
          docker rm websocket-app || true
          docker run -d --name websocket-app --network my-network -p 8081:8081 gery12492/web-socket:1.0.0
          EOF
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}