name: CI/CD for WebSocket App

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21

      - name: Build the project
        run: ./mvnw package

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build -t websocket-app:latest .

      - name: Deploy to Raspberry Pi
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no pi@raspberry-pi-ip << 'EOF'
          docker stop websocket-app || true
          docker rm websocket-app || true
          docker run -d --name websocket-app -p 8080:8080 websocket-app:latest
          EOF
        env:
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
