name: CI/CD for WebSocket App

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Give executable permissions to gradlew
        run: chmod +x ./gradlew

      - name: Check Java version
        run: java -version

      - name: Clean the project
        run: ./gradlew clean

      - name: Build the project
        run: ./gradlew build -x test

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for multiple architectures
        run: |
          docker buildx create --use
          docker buildx build --no-cache --platform linux/arm/v7,linux/amd64  -t gery12492/web-socket:1.0.0 --push .

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # 9️⃣ Configure kubeconfig from GitHub Secret
      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          printf "%s" "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Deploy WEB SOCKET to k3s
        run: |
          # Set environment variables from secrets
          kubectl set env deployment/web-socket SYSTEM_USER_EMAIL="${{ secrets.SYSTEM_USER_EMAIL }}" SYSTEM_USER_PASSWORD="${{ secrets.SYSTEM_USER_PASSWORD }}"
          # Update the deployment image with imagePullPolicy to force pull
          kubectl set image deployment/web-socket web-socket=gery12492/web-socket:1.0.0
          kubectl patch deployment web-socket -p '{"spec":{"template":{"spec":{"containers":[{"name":"web-socket","imagePullPolicy":"Always"}]}}}}'
          # Restart to apply all changes
          kubectl rollout restart deployment/web-socket
